import json
import os

notebook = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Trabajo Adicional: Gestión de Cuadrillas y Órdenes de Trabajo (SmartRoot)\n",
    "\n",
    "El proyecto **SmartRoot** no solo se encarga de monitorear el potencial mátrico y las variables del suelo. Cuando un sensor reporta un nivel de humedad `crítico`, cuando un tensiómetro requiere relleno de agua, o cuando hay que instalar nuevos sensores Gypsum, el sistema genera **Órdenes de Trabajo (OT)** que deben ser atendidas por **Cuadrillas** de técnicos o agricultores.\n",
    "\n",
    "En este cuaderno implementaremos el sistema de asignación de OTs y cuadrillas, cumpliendo con los siguientes requerimientos:\n",
    "1. Modelado usando Programación Orientada a Objetos (POO).\n",
    "2. Demostración de polimorfismo (métodos con el mismo nombre en diferentes clases).\n",
    "3. Lógica de asignación, disponibilidad y programación.\n",
    "4. Propuestas de heurísticas avanzadas."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "class Cuadrilla:\n",
    "    def __init__(self, id_cuadrilla, zona_base, capacidad_diaria_horas):\n",
    "        self.id_cuadrilla = id_cuadrilla\n",
    "        self.zona_base = zona_base\n",
    "        self.capacidad_diaria_horas = capacidad_diaria_horas\n",
    "        self.ordenes_asignadas = []\n",
    "    \n",
    "    def horas_asignadas(self):\n",
    "        return sum(ot.duracion_estimada for ot in self.ordenes_asignadas)\n",
    "    \n",
    "    def disponibilidad(self):\n",
    "        return self.capacidad_diaria_horas - self.horas_asignadas()\n",
    "    \n",
    "    def asignar_ot(self, ot):\n",
    "        if ot.estado != 'Pendiente':\n",
    "            print(f'❌ La OT {ot.id_ot} no está Pendiente.')\n",
    "            return False\n",
    "            \n",
    "        if self.disponibilidad() >= ot.duracion_estimada:\n",
    "            self.ordenes_asignadas.append(ot)\n",
    "            ot.estado = 'Asignada'\n",
    "            print(f'✅ OT {ot.id_ot} asignada a cuadrilla {self.id_cuadrilla}. Disponibilidad restante: {self.disponibilidad()}h')\n",
    "            return True\n",
    "        else:\n",
    "            print(f'⚠️ Cuadrilla {self.id_cuadrilla} sin capacidad para OT {ot.id_ot} (Requiere {ot.duracion_estimada}h, disponible {self.disponibilidad()}h)')\n",
    "            return False\n",
    "            \n",
    "    def mostrar_programacion(self):\n",
    "        print(f'\\n📅 Programación Cuadrilla {self.id_cuadrilla} (Zona: {self.zona_base})')\n",
    "        print(f'   Horas capacidad: {self.capacidad_diaria_horas} | Asignadas: {self.horas_asignadas()}')\n",
    "        print('   ' + '-'*50)\n",
    "        for ot in sorted(self.ordenes_asignadas, key=lambda x: x.prioridad):\n",
    "            print(f'   - [{ot.id_ot}] {ot.tipo_ot()} | Prio: {ot.prioridad} | {ot.duracion_estimada}h | ANS: {ot.ans_horas}h')\n",
    "        print('   ' + '-'*50)\\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Clases de Órdenes de Trabajo (Polimorfismo)\n",
    "\n",
    "A continuación definiremos la clase base abstracta `OrdenTrabajo` y sus clases hijas (`OT_Normal`, `OT_Mantenimiento`, `OT_Urgente`). \n",
    "\n",
    "**¿Qué pasa cuando diferentes clases tienen métodos con el mismo nombre pero diferente funcionalidad (Polimorfismo)?**\n",
    "Al invocar el método (por ejemplo `calcular_costo()` o `ejecutar_accion()`) sobre una lista heterogénea de OTs, Python ejecuta dinámicamente la versión del método que corresponde al tipo real de la instancia. Esto permite escribir código genérico sin necesidad de múltiples bloques `if/elif` evaluando el tipo, facilitando escalar el sistema a decenas de tipos de órdenes distintas."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "from abc import ABC, abstractmethod\n",
    "\n",
    "class OrdenTrabajo(ABC):\n",
    "    def __init__(self, id_ot, zona, duracion_estimada, prioridad, ans_horas):\n",
    "        self.id_ot = id_ot\n",
    "        self.zona = zona\n",
    "        self.duracion_estimada = duracion_estimada\n",
    "        self.prioridad = prioridad       # 1=Alta, 2=Media, 3=Baja\n",
    "        self.ans_horas = ans_horas       # Tiempo máximo esperado\n",
    "        self.estado = 'Pendiente'\n",
    "        \n",
    "    @abstractmethod\n",
    "    def tipo_ot(self):\n",
    "        pass\n",
    "\n",
    "    @abstractmethod\n",
    "    def calcular_costo(self, costo_hora_base):\n",
    "        \"\"\"Método polimórfico: calculará el costo de manera diferente según el tipo de OT\"\"\"\n",
    "        pass\n",
    "\n",
    "class OT_Mantenimiento(OrdenTrabajo):\n",
    "    # Ejemplo: rellenar tensiómetros de agua\n",
    "    def tipo_ot(self):\n",
    "        return 'Mantenimiento Preventivo'\n",
    "        \n",
    "    def calcular_costo(self, costo_hora_base):\n",
    "        # El mantenimiento requiere insumos extra (ej. 15 USD fijos de insumos)\n",
    "        return (self.duracion_estimada * costo_hora_base) + 15\n",
    "\n",
    "class OT_Urgente(OrdenTrabajo):\n",
    "    # Ejemplo: parcela en estrés hídrico extremo, requiere riego inmediato\n",
    "    def tipo_ot(self):\n",
    "        return 'Riego Urgente / Crítica'\n",
    "        \n",
    "    def calcular_costo(self, costo_hora_base):\n",
    "        # Las urgencias pagan hora extra (+50%)\n",
    "        return self.duracion_estimada * (costo_hora_base * 1.5)\n",
    "        \n",
    "class OT_Instalacion(OrdenTrabajo):\n",
    "    # Ejemplo: instalar un nuevo sensor Gypsum\n",
    "    def __init__(self, id_ot, zona, duracion_estimada, prioridad, ans_horas, costo_equipos):\n",
    "        super().__init__(id_ot, zona, duracion_estimada, prioridad, ans_horas)\n",
    "        self.costo_equipos = costo_equipos\n",
    "        \n",
    "    def tipo_ot(self):\n",
    "        return 'Instalación Equipos'\n",
    "        \n",
    "    def calcular_costo(self, costo_hora_base):\n",
    "        # Instalación requiere técnicos especializados y los equipos mismos\n",
    "        return (self.duracion_estimada * costo_hora_base * 1.2) + self.costo_equipos\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Asignación de Órdenes usando Heurística Simple (Prioridad y ANS)\n",
    "A continuación instanciamos las OTs generadas por el sistema SmartRoot y las cuadrillas, y las asignamos automáticamente priorizando las Urgentes."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 1. Instanciar cuadrillas\n",
    "cuadrilla_A = Cuadrilla('C-Alfa', zona_base='Sector Norte', capacidad_diaria_horas=8.0)\n",
    "cuadrilla_B = Cuadrilla('C-Beta', zona_base='Sector Sur', capacidad_diaria_horas=6.0)\n",
    "cuadrillas = [cuadrilla_A, cuadrilla_B]\n",
    "\n",
    "# 2. Instanciar OTs (SmartRoot detecta necesidades)\n",
    "lista_ots = [\n",
    "    OT_Mantenimiento('OT-001', 'Sector Norte', duracion_estimada=2.0, prioridad=3, ans_horas=48), # Rellenar tensiómetro T42\n",
    "    OT_Urgente('OT-002', 'Sector Norte', duracion_estimada=3.5, prioridad=1, ans_horas=4),        # Suelo crítico (psi > 400)\n",
    "    OT_Instalacion('OT-003', 'Sector Sur', duracion_estimada=4.0, prioridad=2, ans_horas=24, costo_equipos=25.0), # Instalar Gypsum\n",
    "    OT_Urgente('OT-004', 'Sector Sur', duracion_estimada=2.0, prioridad=1, ans_horas=3),          # Falla general de riego\n",
    "    OT_Mantenimiento('OT-005', 'Sector Sur', duracion_estimada=3.0, prioridad=3, ans_horas=72)\n",
    "]\n",
    "\n",
    "# Ordenar las OTs por prioridad (menor número = más prioritario) y ANS (más urgente primero)\n",
    "ots_priorizadas = sorted(lista_ots, key=lambda x: (x.prioridad, x.ans_horas))\n",
    "\n",
    "print('⚙️ ASIGNACIÓN AUTOMÁTICA DE OTs')\n",
    "print('='*50)\n",
    "for ot in ots_priorizadas:\n",
    "    # Buscar la cuadrilla de la misma zona con disponibilidad\n",
    "    cuadrilla_ideal = next((c for c in cuadrillas if c.zona_base == ot.zona and c.disponibilidad() >= ot.duracion_estimada), None)\n",
    "    \n",
    "    # Si la cuadrilla de la zona no tiene disponibilidad, buscar cualquiera que la tenga\n",
    "    if not cuadrilla_ideal:\n",
    "        cuadrilla_ideal = next((c for c in cuadrillas if c.disponibilidad() >= ot.duracion_estimada), None)\n",
    "        \n",
    "    if cuadrilla_ideal:\n",
    "        cuadrilla_ideal.asignar_ot(ot)\n",
    "    else:\n",
    "        print(f'🚨 ALERTA: No hay cuadrillas con capacidad para la OT {ot.id_ot} (Prioridad {ot.prioridad})')\n",
    "\n",
    "print('\\n📋 RESULTADO DE LA PROGRAMACIÓN')\n",
    "for c in cuadrillas:\n",
    "    c.mostrar_programacion()\n",
    "\n",
    "print('\\n💰 ANÁLISIS DE COSTOS (Demostración de Polimorfismo)')\n",
    "print('='*50)\n",
    "costo_hora = 20.0 # USD por hora de técnico\n",
    "costo_total = 0\n",
    "for ot in lista_ots:\n",
    "    costo = ot.calcular_costo(costo_hora)\n",
    "    costo_total += costo\n",
    "    print(f'[{ot.id_ot}] {ot.tipo_ot():<25} -> Costo: USD {costo:.2f}')\n",
    "\n",
    "print('-'*50)\n",
    "print(f'COSTO TOTAL ESTIMADO DEL DÍA: USD {costo_total:.2f}')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Propuesta de Heurísticas Avanzadas\n",
    "\n",
    "En lugar de usar solo ordenamiento y búsqueda codiciosa (Greedy) por zona y prioridad, para un sistema empresarial más robusto (a medida que las granjas SmartRoot crezcan), se proponen las siguientes heurísticas:\n",
    "\n",
    "1. **Programación Lineal y OR-Tools:** \n",
    "   Modelar el problema como un VRP (Vehicle Routing Problem) o un problema de asignación con ventanas de tiempo (VRPTW). OR-Tools de Google permitiría minimizar simultáneamente los tiempos de viaje de las cuadrillas, los costos por horas extra y el retraso respecto a los ANS, sujeto a restricciones duras de capacidad diaria. \n",
    "\n",
    "2. **Simulación de Montecarlo (Cumplimiento de ANS):**\n",
    "   Las duraciones de instalación o reparación nunca son exactas (Ej. lluvia fuerte, el suelo dificulta instalar el Gypsum, etc). Usar Montecarlo modelando la duración de las OT usando distribuciones normales o triangulares permite responder: *\"¿Cuál es la probabilidad de que la Cuadrilla A no logre cumplir el ANS de la OT-002 si el terreno presenta problemas?\"*\n",
    "\n",
    "3. **Optimización Multiobjetivo:**\n",
    "   El agrónomo quiere reducir los costos (menor horas extra de cuadrillas) pero también maximizar la salud de la planta (atender rápido las OTs Urgentes). Un algoritmo como NSGA-II encontraría frentes de Pareto que balanceen Costo vs Riesgo Hídrico."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "# Simulación de Montecarlo para el cumplimiento del ANS de la Cuadrilla A\n",
    "# Variables inciertas: duración real de las OTs asignadas a la Cuadrilla A\n",
    "iteraciones = 1000\n",
    "horas_capacidad = cuadrilla_A.capacidad_diaria_horas\n",
    "horas_estimadas_asignadas = cuadrilla_A.horas_asignadas()\n",
    "\n",
    "# Supongamos que la duración real de cada OT varía un +/- 25% con distribución triangular\n",
    "resultados_duracion_total = []\n",
    "\n",
    "for _ in range(iteraciones):\n",
    "    duracion_dia = 0\n",
    "    for ot in cuadrilla_A.ordenes_asignadas:\n",
    "        minimo = ot.duracion_estimada * 0.75\n",
    "        maximo = ot.duracion_estimada * 1.50 # Suele demorarse más, no menos\n",
    "        moda = ot.duracion_estimada\n",
    "        duracion_real = np.random.triangular(minimo, moda, maximo)\n",
    "        duracion_dia += duracion_real\n",
    "    resultados_duracion_total.append(duracion_dia)\n",
    "\n",
    "resultados_duracion_total = np.array(resultados_duracion_total)\n",
    "prob_incumplimiento = np.mean(resultados_duracion_total > horas_capacidad) * 100\n",
    "\n",
    "plt.figure(figsize=(10, 4))\n",
    "plt.hist(resultados_duracion_total, bins=40, color='#457b9d', alpha=0.7, edgecolor='white')\n",
    "plt.axvline(horas_capacidad, color='red', linestyle='--', linewidth=2, label=f'Límite de capacidad ({horas_capacidad}h)')\n",
    "plt.axvline(np.mean(resultados_duracion_total), color='orange', linestyle='-', linewidth=2, label=f'Media simulada ({np.mean(resultados_duracion_total):.1f}h)')\n",
    "\n",
    "plt.title(f'Montecarlo: Incertidumbre en duraciones de Cuadrilla {cuadrilla_A.id_cuadrilla}')\n",
    "plt.xlabel('Horas totales consumidas en el día')\n",
    "plt.ylabel('Frecuencia (Iteraciones)')\n",
    "plt.legend()\n",
    "plt.grid(alpha=0.3)\n",
    "plt.show()\n",
    "\n",
    "print(f'📊 RESULTADOS MONTECARLO ({iteraciones} iteraciones):')\n",
    "print(f'   Horas estimadas planificadas: {horas_estimadas_asignadas:.1f}h')\n",
    "print(f'   Horas reales promedio     : {np.mean(resultados_duracion_total):.1f}h')\n",
    "print(f'   Probabilidad de requerir horas extra: {prob_incumplimiento:.1f}%')\n",
    "print(f'   Horas máximas en peor escenario: {np.max(resultados_duracion_total):.1f}h')\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}

with open('notebooks/06_ordenes_trabajo_mantenimiento.ipynb', 'w', encoding='utf-8') as f:
    json.dump(notebook, f, indent=1, ensure_ascii=False)
print("Notebook 06 creado exitosamente.")
